# Generated by Django 4.2.11 on 2025-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('id_card', models.FileField(upload_to='id_cards/')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payments/')),
            ],
        ),
    ]
