# Generated by Django 4.2.11 on 2025-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
