# Generated by Django 5.2.3 on 2025-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0002_remove_registration_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
